### ISSUE TITLE
User story: Navigation

### ISSUE THREAD

**Issue by ghost** [casopisdrakkar/oar#9]
I should be able to navigate:
1. from issue to main page
2. from the article to issue and main page

**Comment by novotnyr** [comment]
Any suggestions on the link position?
1. issue to main page: click on the huge DRAKKAR title
2. where to put the link to the website?

**Comment by novotnyr** [comment]
Fixed issue HTML and CSS.
Added large 'Drakkar' headline into each article.

**Comment by ghost** [comment]
Still missing on http://drakkar.sk/authors.html and http://drakkar.sk/tags.html

**Comment by ghost** [comment]
Fixed.
